### ISSUE TITLE
What happened pleer.net?

### ISSUE THREAD

**Issue by beratsenv** [Paolo7297/MusicDownloader#1]
I'm joining this site but not work anymore?

**Comment by Paolo7297** [comment]
No idea... I'll find new sources

**Comment by beratsenv** [comment]
Yeah, I found new source ! 

https://my-hit.fm/

Check please.

**Comment by beratsenv** [comment]
I have just reviewed the genre system. Genreactivity.java may  add the system files.

There is also a top music list, a Performers list and also a popular collection list. What do you think?

**Comment by Paolo7297** [comment]
Now it's working again... I'll take a look.
Sorry but i'm busy these days
